Fixed error/incompatibility causing build failure.
Short error: frameworks/opt/net/wifi/libwifi_hal/Android.bp:156:1: "libwifi_hal_vendor_impl_defaults" depends on undefined module "libwifi-hal-qcom"
Full error;
```
[100% 2/2] analyzing Android.bp files and generating ninja file at out/soong/build.matrixx_ice.ninja
FAILED: out/soong/build.matrixx_ice.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"     --out "out"
   --soong_variables out/soong/soong.matrixx_ice.variables -o out/soong/build.matrixx_ice.ninja --kati_suffix -matrixx_ice --kati_enabled -l out/.module_paths/Android.bp.list --available_env out/soong/soong.envir
onment.available --used_env out/soong/soong.environment.used.matrixx_ice.build Android.bp
error: frameworks/opt/net/wifi/libwifi_hal/Android.bp:156:1: "libwifi_hal_vendor_impl_defaults" depends on undefined module "libwifi-hal-qcom".
Module "libwifi_hal_vendor_impl_defaults" is defined in namespace "." which can read these 17 namespaces: ["." "." "device/realme/ice" "hardware/google/interfaces" "vendor/pixel/sounds/common" "vendor/qcom/openso
urce/usb/etc" "hardware/google/pixel" "vendor/oneplus/sm8350-common" "device/oneplus/sm8350-common" "vendor/pixel/themepicker/common" "vendor/realme/ice" "hardware/oplus" "vendor/pixel/gms/common" "hardware/linea
ge/interfaces/power-libperfmgr" "hardware/oplus/overlay/generic" "hardware/oplus/overlay/qssi" "hardware/qcom-caf/common/libqti-perfd-client"]
Module "libwifi-hal-qcom" can be found in these namespaces: ["hardware/qcom-caf/wlan" "hardware/qcom-caf/wlan/qcwcn" "hardware/qcom/wlan" "hardware/qcom/wlan/legacy" "hardware/qcom/wlan/wcn6740" "hardware/qcom/wl
an/wcn7760"]
Or did you mean ["libwifi-hal-bcm"]?
17:08:05 soong bootstrap failed with: exit status 1
```